# Generated by Django 2.0.7 on 2018-10-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textconvertor', '0002_remove_imageviewer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageviewer',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
